import os

# --- SISTEMA E DEBUG ---
DEBUG = True
DEBUG_LOAD = False
DEBUG_TRACE = False
DEBUG_DECISION = False
DEBUG_TRAINING = False

# --- MERCADO ---
SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'AVAX/USDT', 'ENA/USDT', 'DOGE/USDT', 'XMR/USDT'] 
SYMBOLS_TRANING = ['BTC/USDT', 'AVAX/USDT', 'DOGE/USDT']
TIMEFRAME = '5m'
HISTORY_LIMIT = 5000           

# --- IMAGEM (CNN) MANTIDA 64x64 ---
IMG_SIZE = (64, 64)            
IMG_DPI = 100                  
WINDOW_SIZE = 60               

# --- AMBIENTE E CARTEIRA ---
INITIAL_BALANCE = 100000.0
COMMISSION = 0.00075 
ALLOCATION_PER_TRADE = 0.20  
MIN_BALANCE_RESERVE = 50.0   
RESET_WALLET = False

# --- REWARD SHAPING MATEMÁTICO ---
TRADE_PENALTY = 0.01           
PROFIT_WEIGHT = 40.0           
LOSS_WEIGHT = 80.0             
HOLDING_PENALTY = -0.002       
STRICT_STOP_LOSS_REWARD = -0.3 
CONSISTENCY_BONUS = 0.001 

# --- SEGURANÇA ---
USE_STOP_LOSS = True
STOP_LOSS_PCT = 0.02  

# --- IA: TREINAMENTO INICIAL ---
LEARNING_RATE = 1e-4
BATCH_SIZE = 64                
GAMMA = 0.995                  
N_STEPS = 1024                 
TOTAL_TIMESTEPS = 80000        

# --- IA: APRENDIZADO ONLINE LOCAL ---
ONLINE_LEARNING_RATE = 5e-6    
N_STEPS_ONLINE = 512           
UPDATE_EVERY_N_CANDLES = 12    
LOOKBACK_WINDOW_ONLINE = 300   

# --- CAMINHOS ---
MODEL_DIR = os.path.join('bot', 'models')
DATA_DIR = os.path.join('bot', 'data')
