import os

# --- SISTEMA E DEBUG ---
DEBUG = True
DEBUG_LOAD = False
DEBUG_TRACE = False
DEBUG_DECISION = False
DEBUG_TRAINING = False

# --- MERCADO ---
SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'AVAX/USDT', 'ENA/USDT', 'DOGE/USDT', 'XMR/USDT'] 
SYMBOLS_TRANING = ['BTC/USDT', 'AVAX/USDT', 'DOGE/USDT']
TIMEFRAME = '5m'
HISTORY_LIMIT = 5000

# --- IMAGEM (CNN) ---
IMG_SIZE = (64, 64)
IMG_DPI = 100        
WINDOW_SIZE = 60 

# --- AMBIENTE E CARTEIRA ---
INITIAL_BALANCE = 1000.0
COMMISSION = 0.00075 
ALLOCATION_PER_TRADE = 0.20  
MIN_BALANCE_RESERVE = 50.0   
RESET_WALLET = False

# --- REWARD SHAPING (Ajuste para Performance) ---
TRADE_PENALTY = 0.001    
PROFIT_WEIGHT = 20.0           
HOLDING_PENALTY = -0.0005      
STRICT_STOP_LOSS_REWARD = -0.1 
CONSISTENCY_BONUS = 0.001 

# --- SEGURANÇA ---
USE_STOP_LOSS = True
STOP_LOSS_PCT = 0.02  

# --- IA: TREINAMENTO INICIAL (Módulo run_training) ---
LEARNING_RATE = 1e-4
BATCH_SIZE = 32
GAMMA = 0.99  
N_STEPS = 512          
TOTAL_TIMESTEPS = 50000  

# --- IA: APRENDIZADO ONLINE (Módulo run_online_session) ---
ONLINE_LEARNING_RATE = 1e-5    
N_STEPS_ONLINE = 512           
UPDATE_EVERY_N_CANDLES = 12    
LOOKBACK_WINDOW_ONLINE = 300   

# --- CAMINHOS ---
MODEL_DIR = os.path.join('bot', 'models')
DATA_DIR = os.path.join('bot', 'data')
